name: Email
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
          host: smtp.google.com
          account: ${{secrets.usernameEmail}}
          password: ${{secrets.emailPassword}}
          sender: Rishabh
          from: ${{secrets.usernameEmail}}
          subject: Github Actions job result
          body: file://README.md
          attachments: "$GITHUB_WORKSPACE/Rishabh_Verma_SDE_Resume.pdf"
          to: rishabhverma17@gmail.com
