name: Build LaTeX document, check and commit to gh-pages branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: isso.tex
    - name: Check pdf file
      run: |
        file Rishabh_Verma_SDE_Resume.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        set -e
        # configure git
        git config --global user.name "Rishabh Verma"
        git config --global user.email "rishabhverma17@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        # Copy and commit the PDF file
        mkdir -p "$GITHUB_WORKSPACE/deploy"
        cp -f main.pdf "$GITHUB_WORKSPACE/deploy/Rishabh_Verma_SDE_Resume.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git init
        git checkout --orphan gh-pages
        git add main.pdf
        git commit -m "[github actions] deploy"
        git remote add origin git@github.com:rishabhverma17/DevOpsing_Resume.git
        git push --force --set-upstream origin gh-pages
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
