name: Build document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: isso.tex
      - name: Create and upload release
        uses: softprops/action-gh-release@v1
        with:
          files: Resume_RishabhVerma_SDE.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
