name: Build PDF
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: isso.tex
    - name: Check pdf file
      run: |
        file Rishabh_Verma_SDE_Resume.pdf | grep -q ' PDF '
    - name: Upload cv.pdf
      run: |
        # configure git
        git config --global user.name "Rishabh Verma"
        git config --global user.email "rishabhverma17@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 git@github.com:rishabhverma17/DevOpsing_Resume.git "$GITHUB_WORKSPACE/website"
        cp -f Rishabh_Verma_SDE_Resume.pdf "$GITHUB_WORKSPACE/website/file/Rishabh_Verma_SDE_Resume.pdf"
        cd "$GITHUB_WORKSPACE/website"
        git add Rishabh_Verma_SDE_Resume.pdf
        git commit -m "[github actions] update cv"
        git push -f
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
