name: Build LateX Resume 2
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile Version 1
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: resumeFullWidth
    - name: Check pdf files
      run: |
        file resumeFullWidth/main.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        # configure git
        git config --global user.name "Rishabh Verma"
        git config --global user.email "rishabhverma17@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch gh-pages-fullwidth git@github.com:rishabhverma17/DevOpsing_Resume.git "$GITHUB_WORKSPACE/deploy"
        cp -f resumeFullWidth/main.pdf "$GITHUB_WORKSPACE/deploy/Resume_Rishabh_Verma_SDE.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add Resume_Rishabh_Verma_SDE.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
